### ISSUE TITLE
insert TODO or TODO: comment

### ISSUE THREAD

**Issue by gozes** [tarsius/hl-todo#15]
It be really useful if this mode where capable of inserting TODO or TODO: comments.

**Comment by tarsius** [comment]
Like <kbd>C-c C-t</kbd> in Org-Mode? That might be nice, but implementing it is a very low priority for me. Note that I created this package specifically because all the existing solutions provided too many features in my eyes. The library commentary contains this:

> See [this list](http://emacswiki.org/FixmeMode) on the Emacswiki for other packages that implement the same basic features, but which might also provide additional features that you might like, but which I don't deem necessary.

Maybe I will implement this at one point, maybe not.

**Comment by tarsius** [comment]
Probably not.
