### ISSUE TITLE
Bad performance with large files

### ISSUE THREAD

**Issue by seagle0128** [tarsius/hl-todo#22]
Hi, I like this package. But while opening the large files (e.g. `web-mode.el`), the Emacs becomes very slow. It's so slaggy and I have to  go back to `fic-mode`.
My config is GNU Emacs 25.3/26.1, macOS 10.13/Ubuntu 16.04.

**Comment by tarsius** [comment]
`hl-todo` uses Font Lock. I know little about Font Lock internals, but basically you give it a regexp and a face and it then applies that face to the matched text. `hl-todo` uses a function instead of a regexp:

```lisp
(defvar hl-todo-keywords
  `(((lambda (limit)
       (let (case-fold-search)
         (and (re-search-forward hl-todo-regexp limit t)
              (nth 8 (syntax-ppss))))) ; inside comment or string
     (1 (hl-todo-get-face) t t))))
```

Instead of that lambda one could also use the regexp directly. In that case there could be false-positives outside of comments and strings. But you might still want to try that.

The regexp is efficient I think. It is generated like so:

```lisp
(defun hl-todo-set-regexp ()
  "Set the value of `hl-todo-regexp' based on `hl-todo-keyword-faces'."
  (setq hl-todo-regexp
        (concat "\\_<" (regexp-opt (mapcar #'car hl-todo-keyword-faces) t)
                ":?\\_>")))
```

`hl-todo-get-face` should be efficient too:

```lisp
(defun hl-todo-get-face ()
  (let ((face (cdr (assoc (match-string 1) hl-todo-keyword-faces))))
    (if (stringp face)
        (list :inherit 'hl-todo :foreground face)
      face)))
```

I don't see anything that could make this slow, but you might want to experiment by redefining some of the things above to narrow the issue down.

**Comment by tarsius** [comment]
Maybe `syntax-ppss` is slow (I don't know), but the size of the file should not matter here, just the number of matches for `hl-todo-regexp`.

**Comment by seagle0128** [comment]
I did the profiler just now. Hope it's helpful.

<img width="623" alt="screen shot 2018-04-17 at 1 43 35 am" src="https://user-images.githubusercontent.com/140797/38825934-d73bb558-41e0-11e8-91e4-b89ef51847a7.png">

**Comment by tarsius** [comment]
I overlooked that you were talking about a delay when visiting the file, I thought this was about a performance decrease later on. Well that's because of:

```lisp
(font-lock-flush)
(font-lock-ensure)
```

Which causes the whole buffer to be fontified at once. It's unclear how that can be avoided though. It might be possible but will require reading lots of Font Lock code. I don't plan to do that anytime soon. You *might* get away with just removing the second function call.

**Comment by zhaojiangbin** [comment]
I am experiencing slowness similar to this. When `desktop-read` restores large number of buffers in hl-todo mode, `font-lock-ensure` is dominant in memory usage, and significant in CPU usages, according to the profiler.

**Comment by tarsius** [comment]
Please try out #29.

**Comment by seagle0128** [comment]
I was not able to reproduce this issue. Seems good for me.

**Comment by zhaojiangbin** [comment]
It seems to have improved a lot over master. Tested restoring a desktop session with 400+ buffers. The difference in speed is very noticeable between this PR and master at bbccf4a.
