### ISSUE TITLE
`hl-todo-occur` not respecting `hl-todo-keyword-faces`

### ISSUE THREAD

**Issue by Wagk** [tarsius/hl-todo#23]
When running `hl-todo-occur`, the buffer does not color the keywords, leaving them uniform

Example:

<img width="678" alt="weeoe" src="https://user-images.githubusercontent.com/5961525/39045634-fb68b1aa-44c5-11e8-9d2c-cb948959eabd.png">

Current configuration:

<img width="408" alt="emacs_2018-04-20_18-08-40" src="https://user-images.githubusercontent.com/5961525/39045611-e7a0a452-44c5-11e8-9575-ab725bd4d545.png">

**Comment by Wagk** [comment]
Or perhaps I'm configuring it wrongly? Please advise.

**Comment by tarsius** [comment]
This is the definition of that command:

```lisp
(defun hl-todo-occur ()
  "Use `occur' to find all TODO or similar keywords.
This actually finds a superset of the highlighted keywords,
because it uses a regexp instead of a more sophisticated
matcher."
  (interactive)
  (occur hl-todo-regexp))
```

In other words, the coloring is done by `hl-todo-mode`, which has to be enabled separately.

**Comment by Wagk** [comment]
I've enabled it through a hook, and the problem is currently persisting

<img width="689" alt="emacs_2018-04-20_18-57-55" src="https://user-images.githubusercontent.com/5961525/39047549-dd37a734-44cc-11e8-8524-b9238aeb5b25.png">

is adding a hook to occur-mode insufficient?

**Comment by tarsius** [comment]
While `occur` keeps the faces used in the other buffer when it displays the lines that contain a match in `*Occur*`, it applies its own face to the part of the lines that actually matched. I don't see that in your screenshot and I don't know why that is. Maybe this is an intentional change by the author of your theme - maybe because the maintainers wanted to avoid faces to be overwritten as would usually happen.

Also some of the matches actually preserve their face that `hl-todo-mode` added in the other buffer. I am guessing that this is because that part of that buffer has already been re-font-lock-ified after `hl-todo-mode` has been turned on, while the other parts have not.

> is adding a hook to occur-mode insufficient?

No. `hl-todo-mode` is intended to be turned on (more or less) permanently in a (usually) file-visiting buffer. `hl-todo-occur` is just a user contributed command that I do not use but merged because it sounded somewhat useful. How the matched keywords are displayed in the `*Occur*` buffer is under `occur`'s control (and used theme's).

It is weird that some parts use the `hl-todo`-specified colors while others do not, and I *speculate* that this is because other parts have not re-font-lock-ified yet. I am guessing that the `font-lock` functions that `hl-todo-mode` calls to do the fonification do perform work on the visible portion while they delay (using timers or such) work on the other parts of the buffer until Emacs returns to the command loop, at which point `occur` has already taken the not-re-fontified parts and displayed them in `*Occur*`.

I do not intend to investigate this further or to support your use-case better. This package has been designed with the assumption that `hl-todo-mode` gets permanently turned on. Sorry.

**Comment by tarsius** [comment]
Having looked at the original screenshot again, I realize now that the weird look of the second `*Occur*` buffer is due to `hl-todo-mode` being turned on in *that* buffer. This won't work properly because that buffer does nto use Font-Lock, which `hl-todo-mode` relies on.
