### ISSUE TITLE
Idea: List current feature branch todos

### ISSUE THREAD

**Issue by arronmabrey** [tarsius/hl-todo#41]
@tarsius First off I'm a big fan of the work you do and very appreciative of it. :-)

I had a thought, I have been wanting to figure out a todo methodology this fits in nicely with my workflow. Specifically as I'm reading through code paths, preparing to work on a feature branch, I'd like to commit #TODO commits along the way (on said feature branch) and have a way to list/navigate all the TODOs whereby the TODO searching only looks for the TODOs added in the current feature branch only, not across all history in the project which could include other team members and other noise from other stories.

With your experience with this package and magit does anything possible come to mind that could help accomplish that?

Thanks,
-- Arron

**Comment by tarsius** [comment]
This sounds like something that could be added to [`magit-todos`](https://github.com/alphapapa/magit-todos). Instead of searching the worktree, it could maybe be taught to search the added lines in the `@{upstream}..` diff instead. What you think @alphapapa?

**Comment by arronmabrey** [comment]
Thanks! 🙏 magit-todos looks really interesting and close to what I’m
looking for! I’m curious of @alphapapa’s thoughts as well. 🙂

Thanks,
-- Arron

**Comment by alphapapa** [comment]
This is an interesting idea.  Implementing it would basically amount to two steps, I think:

1.  Implement a `magit-todos` scanner function that parses the diff from git rather than the worktree.  As long as it returns results in the same format, the rest of `magit-todos`'s code will work.
2.  Implement UI to make it easier to choose this "mode" of scanning, since users probably won't want to use it on e.g. `master`.

**Comment by alphapapa** [comment]
@arronmabrey If you're interested, please try the code in that issue and continue the discussion there.

**Comment by tarsius** [comment]
The feature was merged into `magit-todos`' master.
