### ISSUE TITLE
Only highlighting in comments

### ISSUE THREAD

**Issue by seagle0128** [tarsius/hl-todo#42]
Hi, `hl-todo` is very useful and I love it. I have some ideas and requests here.

1. In `prog-mode`, the keywords are just in comments usually. So is it possible to just highlight keywords in comments, while not strings and codes? That's annoying.
1. It seems `hl-todo` uses `font-lock`. Maybe `overlay` is a better solution? like [symol-overlay](https://github.com/wolray/symbol-overlay).

**Comment by tarsius** [comment]
1. While working on a feature branch, I often have doc-strings like `"TODO"`. That's useful.

   But I have tried to do what you are suggesting before but without success. I have just tried again and think I now why it didn't work properly; it was a special case of the bug fixed with cdc22667f4c7dc3781390c7f9dc8fe2f2c325147.

   Please give the `face-limit` branch a try. I could also use some help thinking of a better option name and doc-string.

2. Why? There has to be a *very* compelling reason for me to rip out the core of this package and replace it with a new implementation and then deal with the regressions.

   Regarding `symbol-overlay`: While I use `symbol-overlay` I considered its use of overlay to be a mistake for a long time, though https://github.com/wolray/symbol-overlay/commit/ccf791377adc5d9158ffac626db2f639197a0584 fixed the issue I was having.

**Comment by seagle0128** [comment]
1. It does make sense. Some people like add "TODO" in doc-strings. Ad option is a good idea here.
1. `font-lock` is slow for the large files. `overlay` has better performance?

**Comment by tarsius** [comment]
> `font-lock` is slow for the large files. `overlay` has better performance?

We already do #29 for performance reasons. I don't think abandoning font-lock completely and hoping for the best would do much good.

**Comment by seagle0128** [comment]
I am fine if the performance issue was addressed. I am closing it. Thanks!
